import fs from "node:fs/promises";
import path from "node:path";
import { ComposeContext } from "../context/types";
import { ConfigOptions, IFrameworkAdapter } from "./interface/IFrameworkAdapter";
import { writeFileIfMissing } from "../utils/files";
import { runCommand } from "../utils/exec";
import { resolveCatalogSourceForRead } from "../utils/soliditySources";

function ensureTomlSectionSettings(
  content: string,
  section: string,
  settings: Record<string, string>,
): string {
  const lines = content.replace(/\r\n/g, "\n").split("\n");
  if (lines.at(-1) === "") lines.pop();

  let sectionIndex = lines.findIndex((line) => line.trim() === `[${section}]`);
  if (sectionIndex === -1) {
    if (lines.length > 0 && lines.at(-1)?.trim() !== "") lines.push("");
    sectionIndex = lines.length;
    lines.push(`[${section}]`);
  }

  let sectionEnd = lines.findIndex(
    (line, index) => index > sectionIndex && /^\s*\[[^\]]+\]\s*$/.test(line),
  );
  if (sectionEnd === -1) sectionEnd = lines.length;

  const sectionLines = lines.slice(sectionIndex + 1, sectionEnd);
  const missingSettings = Object.entries(settings)
    .filter(([key]) => !sectionLines.some((line) => new RegExp(`^\\s*${key}\\s*=`).test(line)))
    .map(([key, value]) => `${key} = ${value}`);

  lines.splice(sectionEnd, 0, ...missingSettings);
  return `${lines.join("\n")}\n`;
}

/** Framework adapter for Foundry-based Diamond projects. */
const adapter: IFrameworkAdapter = {
  getContractSourceRoot(projectRoot: string): string {
    return path.join(projectRoot, "src");
  },

  getScriptRoot(projectRoot: string): string {
    return path.join(projectRoot, "script");
  },

  getTestRoot(projectRoot: string): string {
    return path.join(projectRoot, "test");
  },

  async resolveSoliditySourcePath(ctx: ComposeContext, sourcePath: string): Promise<string> {
    return resolveCatalogSourceForRead(sourcePath);
  },

  async initProject(ctx: ComposeContext): Promise<void> {
    const root = String(ctx.param.projectRoot ?? "");
    const installDeps = ctx.param.installDeps !== false;

    await runCommand("forge", ["init", "."], { cwd: root });

    if (installDeps) {
      await runCommand("forge", ["install", "Perfect-Abstractions/Compose"], { cwd: root });
    } else {
      await fs.mkdir(path.join(root, "lib"), { recursive: true });
    }

    await Promise.all([
      fs.rm(path.join(root, "src"), { recursive: true, force: true }),
      fs.rm(path.join(root, "test"), { recursive: true, force: true }),
      fs.rm(path.join(root, "script"), { recursive: true, force: true }),
    ]);

    await fs.mkdir(path.join(root, "test"), { recursive: true });
    await fs.mkdir(path.join(root, "script"), { recursive: true });
  },

  async writeConfig(ctx: ComposeContext, opts: ConfigOptions): Promise<void> {
    const root = String(ctx.param.projectRoot ?? "");

    const foundryTomlPath = path.join(root, "foundry.toml");
    let foundryToml = "";
    try {
      foundryToml = await fs.readFile(foundryTomlPath, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }

    const updatedFoundryToml = ensureTomlSectionSettings(foundryToml, "profile.default", {
      solc: `"${opts.compilerVersion}"`,
      optimizer: "true",
    });

    const remappings = "@perfect-abstractions/compose/=lib/Compose/src/\n";
    const gitignore = "out/\ncache/\n";

    let readme: string;
    try {
      const templatePath = path.resolve(process.cwd(), "src/templates/readme/foundry-readme.md");
      const template = await fs.readFile(templatePath, "utf8");
      readme = template.replace(/\{\{PROJECT_NAME\}\}/g, opts.projectName);
    } catch {
      readme = `# ${opts.projectName}\n\nGenerated by compose init\n`;
    }

    if (updatedFoundryToml !== foundryToml) {
      await fs.writeFile(foundryTomlPath, updatedFoundryToml, "utf8");
    }
    await writeFileIfMissing(path.join(root, "remappings.txt"), remappings);
    await writeFileIfMissing(path.join(root, ".gitignore"), gitignore);
    await fs.writeFile(path.join(root, "README.md"), readme, "utf8");
  },
};

export const foundryAdapter = adapter;
