import fs from "node:fs/promises";
import path from "node:path";
import { ComposeContext } from "../context/types";
import { ConfigOptions, IFrameworkAdapter } from "./interface/IFrameworkAdapter";
import { writeFileIfMissing } from "../utils/files";
import { runCommand } from "../utils/exec";
import { isComposePackagePath, resolveCatalogSourceForRead } from "../utils/soliditySources";
import { ScaffoldingModule } from "../modules/scaffolding/module";
import { CLI_ROOT } from "../utils/cliRoot";

/** Framework adapter for Hardhat-based Diamond projects. */
const adapter: IFrameworkAdapter = {
  getContractSourceRoot(projectRoot: string): string {
    return path.join(projectRoot, "contracts");
  },

  getScriptRoot(projectRoot: string): string {
    return path.join(projectRoot, "scripts");
  },

  getTestRoot(projectRoot: string): string {
    return path.join(projectRoot, "test");
  },

  async resolveSoliditySourcePath(ctx: ComposeContext, sourcePath: string): Promise<string> {
    return resolveCatalogSourceForRead(sourcePath);
  },

  async initProject(ctx: ComposeContext): Promise<void> {
    const root = String(ctx.param.projectRoot ?? "");
    const projectName = String(ctx.param.projectName ?? "my-diamond");
    const toolbox = String(ctx.param.toolbox ?? "ethers");

    const devDeps: Record<string, string> =
      toolbox === "viem"
        ? {
            hardhat: "^3.8.0",
            "@nomicfoundation/hardhat-toolbox-viem": "^5.0.0",
          }
        : {
            hardhat: "^3.8.0",
            "@nomicfoundation/hardhat-toolbox-mocha-ethers": "^3.0.0",
          };

    const packageJson = {
      name: projectName,
      version: "0.1.0",
      description: "Diamond project generated by Compose CLI",
      type: "module",
      main: "index.js",
      scripts: {
        build: "npx hardhat compile",
        test: "npx hardhat test",
      },
      keywords: ["solidity", "ethereum", "smart-contracts", "diamonds", "ERC-2535"],
      author: "",
      license: "MIT",
      dependencies: {
        "@perfect-abstractions/compose": "latest",
      },
      devDependencies: devDeps,
    };

    await fs.writeFile(path.join(root, "package.json"), JSON.stringify(packageJson, null, 2));
  },

  async writeConfig(ctx: ComposeContext, opts: ConfigOptions): Promise<void> {
    const root = String(ctx.param.projectRoot ?? "");
    const toolbox = String(ctx.param.toolbox ?? "ethers");
    const selectedFacets = ScaffoldingModule.getSelectedFacets(ctx);
    const packageFacetPaths = selectedFacets
      .map((facet) => facet.entry.path)
      .filter(isComposePackagePath);

    const npmFilesToBuild = packageFacetPaths.length > 0
      ? `    npmFilesToBuild: ${JSON.stringify(packageFacetPaths, null, 4).replace(/\n/g, "\n    ")},\n`
      : "";

    const toolboxImport =
      toolbox === "viem"
        ? `import hardhatToolboxViem from "@nomicfoundation/hardhat-toolbox-viem";`
        : `import hardhatToolboxMochaEthers from "@nomicfoundation/hardhat-toolbox-mocha-ethers";`;
    const toolboxPlugin = toolbox === "viem" ? "hardhatToolboxViem" : "hardhatToolboxMochaEthers";

    const hardhatConfig = `import { defineConfig } from "hardhat/config";
${toolboxImport}

export default defineConfig({
  plugins: [${toolboxPlugin}],
  solidity: {
${npmFilesToBuild}    profiles: {
      default: {
        version: "${opts.compilerVersion}",
        settings: {
          optimizer: {
            enabled: true,
          },
        },
      },
      production: {
        version: "${opts.compilerVersion}",
        settings: {
          optimizer: {
            enabled: true,
          },
        },
      },
    },
  },
  paths: {
    sources: "./contracts",
    tests: "./test",
    cache: "./cache",
    artifacts: "./artifacts",
  },
});
`;

    await fs.writeFile(path.join(root, "hardhat.config.ts"), hardhatConfig);

    const tsconfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./contracts",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["contracts/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}`;

    await fs.writeFile(path.join(root, "tsconfig.json"), tsconfig);

    const gitignore = `node_modules/
.cache/
artifacts/
dist/
.env
`;

    await fs.writeFile(path.join(root, ".gitignore"), gitignore);

    let readme: string;
    try {
      const templatePath = path.resolve(CLI_ROOT, "src/templates/readme/hardhat-readme.md");
      const template = await fs.readFile(templatePath, "utf8");
      readme = template.replace(/\{\{PROJECT_NAME\}\}/g, opts.projectName);
    } catch {
      readme = `# ${opts.projectName}\n\nGenerated by compose init\n`;
    }
    await writeFileIfMissing(path.join(root, "README.md"), readme);

    await fs.mkdir(path.join(root, "test"), { recursive: true });

    if (opts.installDeps) {
      await runCommand("npm", ["install"], { cwd: root });
    }
  },
};

export const hardhatAdapter = adapter;
