/** Error codes for lock file validation */
export const LockFileErrorCode = {
  INVALID_JSON: "LOCK_FILE_INVALID_JSON",
  MISSING_COMPOSE_VERSION: "LOCK_FILE_MISSING_COMPOSE_VERSION",
  MISSING_DEPLOYMENTS: "LOCK_FILE_MISSING_DEPLOYMENTS",
  INVALID_DIAMOND_ADDRESS: "LOCK_FILE_INVALID_DIAMOND_ADDRESS",
  INVALID_FACET_ADDRESS: "LOCK_FILE_INVALID_FACET_ADDRESS",
  INVALID_FACET_HASH: "LOCK_FILE_INVALID_FACET_HASH",
  INVALID_LAST_SYNC: "LOCK_FILE_INVALID_LAST_SYNC",
  INVALID_TX_HASH: "LOCK_FILE_INVALID_TX_HASH",
} as const;
